name: Build Notes and Trigger Main Site Deploy

on:
  push:
    branches:
      # Trigger on push to this branch in your notes repository
      - main

permissions:
  contents: read # Permissions needed to checkout this repository

jobs:
  build-and-trigger: # Renamed job for clarity
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your notes repository code
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Keep if Quartz uses Git history

      # Step 2: Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a version compatible with Quartz

      # Step 3: Installs Quartz dependencies and builds the notes site
      # The built files will be in ./quartz/public (but NOT deployed from here)
      - name: Install Dependencies and Build Quartz
        run: |
          npm install
          npx quartz build
        working-directory: ./quartz # Run inside the ./quartz directory

      # Step 4: Trigger the deployment workflow in your main Astro site repository
      # This replaces the old step that tried to push files directly
      - name: Trigger Astro Site Deployment
        uses: peter-evans/repository-dispatch@v3 # Using v3
        with:
          # You need to create a Personal Access Token (Classic) with 'repo' scope
          # Add this PAT as a secret named DISPATCH_PAT in THIS (MATH 140A) repository's Actions secrets
          token: ${{ secrets.DISPATCH_PAT }}
          # The target repository (your Astro site)
          repository: pink10000/pink10000.github.io
          # A custom name for the event - your Astro workflow must listen for this type
          event-type: deploy-notes
          # Optional: You can send data if needed by the Astro workflow
          # client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'